### ISSUE TITLE
How to configure the datasource on Grafana?

### ISSUE THREAD

**Issue by tinproject** [camptocamp/grafana-prometheus-alertmanager-datasource#1]
First, thanks for the plugin! 

I've just installed grafana 4.6 and the `camptocamp-prometheus-alertmanager-datasource` plugin. But I cant' find where to define the alertmanager url for the datasource.

Grafana only prompts for a name, ant when save it shows an error:

![prom-alert-grafana-error](https://user-images.githubusercontent.com/3742174/32164700-96455590-bd60-11e7-8b2b-27f6bacfde2a.png)

Please add docs on how to configure the datasource.

**Comment by cryptobioz** [comment]
Hi,
I cannot reproduce...
Which OS are you using? Do you use a Docker container?
How did you install the AlertManager plugin?

**Comment by tinproject** [comment]
Yes, we use a custom docker container with this dockerfile:
```
FROM grafana/grafana:4.6.0

COPY grafana.ini /etc/grafana/grafana.ini

# Plugin installation
RUN mkdir -p /grafana-plugins

RUN grafana-cli --pluginsDir "/grafana-plugins" plugins install other-plugins..
RUN grafana-cli --pluginsDir "/grafana-plugins" plugins install camptocamp-prometheus-alertmanager-datasource
RUN grafana-cli --pluginsDir "/grafana-plugins" plugins ls

ENV GF_PATHS_PLUGINS="/grafana-plugins"
```

Alert manager is on other containers on the same network.

**Comment by tinproject** [comment]
@cryptobioz Works ok with Grafana 4.6.1. Perhaps is related to https://github.com/grafana/grafana/issues/9509
