### ISSUE TITLE
version 1.0.0 cant be install from https://grafana.com/grafana/plugins

### ISSUE THREAD

**Issue by attachmentgenie** [camptocamp/grafana-prometheus-alertmanager-datasource#102]
there 0.0.8 is the latest version available. when installing 0.0.8 it also reported to be unsigned

**Comment by manzsolutions-lpreis** [comment]
You know this is one of the most recent open issues (#93), visible on the first page?

**Comment by attachmentgenie** [comment]
must have read over it

**Comment by cryptobioz** [comment]
I'm sorry but we're still waiting for the integration of this release in the Grafana's plugins list: https://github.com/grafana/grafana-plugin-repository/projects/2#card-54796691
