### ISSUE TITLE
Seeing "no data" after upgrading to grafana 8.0.0

### ISSUE THREAD

**Issue by aschleifer** [camptocamp/grafana-prometheus-alertmanager-datasource#106]
Today grafana 8.0.0 came out and after upgrading out alertmanager dashboard shows no data:

![image](https://user-images.githubusercontent.com/4940026/121180988-ce181600-c861-11eb-91fa-7f3b98c8df40.png)

We are using the latest release (1.0.0) of this data source.

Is this an error on our side or an incompatibility between this data source and grafana 8?

**Comment by CatShadow44** [comment]
Hi, 
the same for me,
it was ok with verison 0.0.8 and grafana 7
anyone can help please?

**Comment by jjneely** [comment]
I've upgraded Grafana 7.3.3 to 7.5.3 and the upgrade grabbed the Alertmanager datasource 1.0.0.  All I see for all Alertmanager queries is "no data"

**Comment by jjneely** [comment]
This problem is caused by added features on the query panel that the older JSON definition doesn't include.  There is a toggle for selecting "active" alerts that was off...thus showing no data.  Turning it on showed me the expected active alerts.

**Comment by CatShadow44** [comment]
> This problem is caused by added features on the query panel that the older JSON definition doesn't include. There is a toggle for selecting "active" alerts that was off...thus showing no data. Turning it on showed me the expected active alerts.

In my case, i activated this "active alert" switch. No more result, always 'no data'

**Comment by aschleifer** [comment]
> This problem is caused by added features on the query panel that the older JSON definition doesn't include. There is a toggle for selecting "active" alerts that was off...thus showing no data. Turning it on showed me the expected active alerts.

Changing the queries to "active" doesn't change anything for me.

**Comment by CatShadow44** [comment]
ok, i think i found the reason:
this is not the same principle as the previous version: to get the wanted result on alert count, you have to add a transform:
field from calculation:
- field: alertstatus_code
- calculation: total

and in the query: filter severity or alert name as you want.

this solution works for me

**Comment by aschleifer** [comment]
Hm maybe this should be reflected in https://grafana.com/grafana/dashboards/8010 which is the dashboard I use for the alertmanager data source

**Comment by CatShadow44** [comment]
i saw something strange:
when you display data as table, the result is ok.
when you want stats, there is no data

**Comment by wHiteeeeeeeee** [comment]
Yes, that's right. When switch to table it shows all alerts. If single stat - "no data"

**Comment by CatShadow44** [comment]
when can go through the issue with add fields from calculation but it's not very convenient

**Comment by peppermor** [comment]
Same story here got data after setting active to true but only on table

**Comment by cryptobioz** [comment]
For singlestat panels, you must do a transformation. Edit your panel, click on "Transform", click on "Reduce", then change the "Calculations" to "Count".
![2021-07-08_14-13](https://user-images.githubusercontent.com/7858427/124919717-d6957500-dff6-11eb-8e69-966033a07108.png)

**Comment by cryptobioz** [comment]
I just added a documentation regarding this configuration: https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource#singlestat
