### ISSUE TITLE
Sign the plugin

### ISSUE THREAD

**Issue by znerol** [camptocamp/grafana-prometheus-alertmanager-datasource#108]
**Grafana 8** requires plugins to be signed . Please [sign the plugin](
https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/) when publishing a new version.

**Workaround**: unsigned plugins can be [whitelistet](https://grafana.com/docs/grafana/latest/administration/configuration/#allow_loading_unsigned_plugins).

**Comment by hbollon** [comment]
All plugins submitted on Grafana Cloud are now signed :+1: 
Also, I updated our release workflow to upload signed plugin packages directly to Github Releases for faster delivery. Btw, v1.1.0 was released and its package is available here: https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/releases/tag/v1.1.0 (and submit on Grafana Cloud awaiting for review)
