### ISSUE TITLE
Severity NaN for alphabetic value 

### ISSUE THREAD

**Issue by blauzattoo** [camptocamp/grafana-prometheus-alertmanager-datasource#11]
Hi There

First off... nice plugin!

Severity cannot be displayed as we do not use a numeric representation. The Prometheus documentation does not prescribe this field to be an integer. In our case we use keywords like "Critical", "Warning" or "Info".

Is there a possibility to have this label parsed without converting it to int?

**Comment by lelvisl** [comment]
++

**Comment by dulman** [comment]
+1

**Comment by cryptobioz** [comment]
The PR #13 adds the possibility to define keywords as severity levels which should fix this issue.
