### ISSUE TITLE
Use visualization with query count but not show value

### ISSUE THREAD

**Issue by tainguyenbp** [camptocamp/grafana-prometheus-alertmanager-datasource#111]
![image](https://user-images.githubusercontent.com/14048946/125224573-152d7700-e2f8-11eb-8ac4-d78e0ad14b25.png)
hello everybody,

I just upgraded plugin camptocamp-prometheus-alertmanager-datasource version 1.0.0 But I had a problem when I excute query in my grafana.
It doesn't count the alert value with job, severity when I use visualization stats (this picture above) but I use visualization table then it is show value (this picture below).
![image](https://user-images.githubusercontent.com/14048946/125225431-7dc92380-e2f9-11eb-9854-7ff2f9bc151f.png)

Can anyone help me?
tks you so much

**Comment by tainguyenbp** [comment]
anyone can help me? please

**Comment by cryptobioz** [comment]
To use the stat panel, you must apply a transformation in order to display the total count. Please follow this documentation: https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource#stat

**Comment by tainguyenbp** [comment]
yeah tks you for support
I done issue
