### ISSUE TITLE
plugin problem with Grafana 8.0.3

### ISSUE THREAD

**Issue by pablozone** [camptocamp/grafana-prometheus-alertmanager-datasource#112]
It seems there is a problem with query. Query returns no result.
![query](https://user-images.githubusercontent.com/29774180/125622373-edf9c2ec-69e2-42eb-9d6a-aeda3c1b1e94.PNG)
![datasource_config](https://user-images.githubusercontent.com/29774180/125622398-b9878ca6-9a54-4485-8f28-a54d58bd704b.png)

**Comment by admover** [comment]
It's same in Grafana 8.1.1

**Comment by xuanyuanaosheng** [comment]
The grafana officical dashboard 
1.  https://grafana.com/grafana/dashboards/8010
2.  https://grafana.com/grafana/dashboards/12947

can not work on grafana 8.3.0
