### ISSUE TITLE
install plugin 1.0.0

### ISSUE THREAD

**Issue by liuyanmei069** [camptocamp/grafana-prometheus-alertmanager-datasource#113]
Using the command to install the plug-in  ”./grafana-cli plugins install camptocamp-prometheus-alertmanager-datasource“，
but unavailable。
![image](https://user-images.githubusercontent.com/25581778/126452191-6b2063fd-5887-4cb2-ac44-549e79cd37a2.png)

**Comment by hbollon** [comment]
I tried to do exactly the same on a fresh Docker container and I doesn't achieve to reproduce your issue. Everything works well.
I think your problem is related to your dashboard or configuration.
