### ISSUE TITLE
Not all Annotations are visible

### ISSUE THREAD

**Issue by stamina11** [camptocamp/grafana-prometheus-alertmanager-datasource#115]
I have noticed that not all of the annotations that i add in alertrules in Prometheus are coming through to Grafana so i can't manipulate them.
I am not setting any filters and it's bringing in alerts for all of the Receivers. But as you can see 'grafana', 'loki' or 'summary' are not coming through. If i filter out to just those types of alerts i will see them. Is this by design or a bug?

**Comment by andriimaryskevych** [comment]
Hey, I am facing the same issue, but with the labels. After reading the source code I figured out why this happens. In short - annotations and labels from the first item only are taken into account. Meaning - if you receive a response with 10 alerts, and the alerts have slightly different annotations and labels you will get only the labels and annotations that are in the first alert.

Why this happens - the method `buildDataFrame` on the line [95](https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/blob/master/src/DataSource.ts#L95) collects all possible annotations that it has received from the API. So an array of arrays is created. The `.flat()` method should be called on it, but instead, it is called on each array item in `.reduce()` callback.
An example of what happens:
```
> const arr = [[1], [1,2], [1,2,3]];
> arr.reduce(foo => foo.flat())
[ 1 ]
> arr.flat()
[ 1, 1, 2, 1, 2, 3 ]
```

**Comment by hbollon** [comment]
Hey! 
The associated PR was merged. Additional tests must be done and a release will be release very soon :wink: 
Thanks for your contributions!
