### ISSUE TITLE
get  Object(...)(...).fetch is not a function ERROR 

### ISSUE THREAD

**Issue by Matt-labor** [camptocamp/grafana-prometheus-alertmanager-datasource#117]
When I  config the plugin as a datasource, it can be successfully updated, but also get an **Object(...)(...).fetch is not a function** error. The same error occurs when I query from the dashboards. Does anyone know what's going on? 
By the way, the grafana version is v7.1.5 and alertmanger plugin version is v1.0.0.

![image](https://user-images.githubusercontent.com/6867946/129826729-31e4afb9-e286-4c82-a93e-74e4acdae343.png)
![image](https://user-images.githubusercontent.com/6867946/129826980-f7baedf6-90a6-44fc-be5b-b7e24b17455e.png)

**Comment by boholder** [comment]
> Hi guys, Can you retry with v1.2.0 and check if your issue persist please?

Grafana: 7.3.6 linux amd 64 (**not 7.3.5 as origin issue**)
Plugin: v1.2.0

Configurate the alertmanager's datasource, then click "Save&Test" button, the error message is:

```
Object(...) is not a function
```

(Cheer up, you already removed one layer of calling...) I've checked Grafana's log but no log mentioned this datasource error (don't know if there are some configs for changing logging level etc.), sorry.

**Comment by malhussan** [comment]
@hbollon Thanks for the fix! Can you please publish it to https://grafana.com/grafana/plugins/camptocamp-prometheus-alertmanager-datasource/?

**Comment by yelhani** [comment]
@hbollon I can confirm that I had the same error with the version 7.9.8 of grafana!

**Comment by hbollon** [comment]
Hi guys!
Sorry for the delay, I will submit the new release to Grafana.com and keep you updated :+1:

**Comment by yelhani** [comment]
@hbollon I can confirm that I had the same error with the version 7.9.8 of grafana!

**Comment by hbollon** [comment]
The new version v1.2.1 is now available on grafana.com :+1:
