### ISSUE TITLE
Lodash 4.17.20 dependency vulnerable

### ISSUE THREAD

**Issue by ligreman** [camptocamp/grafana-prometheus-alertmanager-datasource#119]
There is a vulnerability in lodash 4.17.20 that is solved in 4.17.21

https://github.com/advisories/GHSA-35jh-r3h4-6jhm

It's advisable to update the plugin dependency on lodash to this new version.

Thanks!

**Comment by hbollon** [comment]
Done and will be released in the next release which coming very soon :+1:
