### ISSUE TITLE
Показывает 0 на панели несмотря на алерт

### ISSUE THREAD

**Issue by eliceyka** [camptocamp/grafana-prometheus-alertmanager-datasource#121]
![image](https://user-images.githubusercontent.com/90947918/144695197-49563f52-541c-41f6-a102-d39342fd3e69.png)
![image](https://user-images.githubusercontent.com/90947918/144695221-817cb915-98f3-4cac-8a2c-a014058e7514.png)

Добрый день, проблема следующего характера, подключил алертменеджер, настроил всё хорошо, и даже показывает в дате что есть действующий алерт, но почему-то показывает всё равно "0" на панели, кто-нибудь встречал? От чего так?

**Comment by zwoefler** [comment]
Hope google translate translated well:

Have a look at the README-file at the very bottom.
To use stat panels, you must apply a transformation to your metrics:
   1.  Edit your panel and open the "Transform" tab.
    2. Select "Reduce" and change the "Calculations" to "Count"

Надеюсь, гугл перевод переведен хорошо: 

Взгляните на README-файл в самом низу. 
Чтобы использовать панели статистики, необходимо применить преобразование к метрикам: 
  1. Отредактируйте панель и откройте вкладку "Трансформирование" (Transform). 
  2. Выберите "Уменьшить" (Reduce) и измените "Расчеты" (Calculations) на "Количество" (Count)
