### ISSUE TITLE
Grafana 8.4.4] After grafana upgrade Alertmanager datasource started behaving strange. One time displaying alarm annotation next time labels

### ISSUE THREAD

**Issue by tahchiev** [camptocamp/grafana-prometheus-alertmanager-datasource#125]
[](https://user-images.githubusercontent.com/103194805/162448707-2c50ad9e-9cea-4369-8e5c-71e536fa5123.png)[](https://user-images.githubusercontent.com/103194805/162448619-253e16ce-c230-471d-af26-d4d6520d9266.png)After upgrade from 7.5.0 to 8.4.4 alert manager data source (camptocamp-prometheus-alertmanager-datasource) started to behave differently. It used to show only alarm labels as a table but now started rotating in time showing alarm labels or annotations. I cannot catch why and at what interval or how to control it.
Labels:
![image](https://user-images.githubusercontent.com/103194805/167413314-ec04cc14-84e8-4b5a-914f-852b8063390a.png)
Annotations:
![image](https://user-images.githubusercontent.com/103194805/162680564-2aa4c91d-73b2-4764-98b1-15dbdb531d12.png)

Any ideas?or recommendations?

**Comment by hbollon** [comment]
Hi @tahchiev,
I think it's a mistake but your screens are identical.
I will try to reproduce your issue on my side and keep your updated. In the meantime, I released v1.1.0 which is not yet approved by grafana cloud but available in Github releases. Can you give it a try and check if your problem persist?

**Comment by tahchiev** [comment]
Just updated, the pic to see difference. I will test with 1.1.0 and let you know
