### ISSUE TITLE
The 1.2.1 plugin version is not available in the official Grafana repo

### ISSUE THREAD

**Issue by ozloozlo** [camptocamp/grafana-prometheus-alertmanager-datasource#133]
The 1.2.1 plugin version is not available in the official Grafana repo
https://grafana.com/grafana/plugins/camptocamp-prometheus-alertmanager-datasource/
Any plans to have it updated?
![Screenshot from 2022-06-27 12-52-37](https://user-images.githubusercontent.com/20371113/175914621-b6e4f9d0-bac0-4046-9e80-2e05995beed8.png)

**Comment by hbollon** [comment]
Hi @ozloozlo 
It is submitted, I'm waiting validation by the team now :+1:

**Comment by hbollon** [comment]
It is now available :+1:
