### ISSUE TITLE
Wrong logo

### ISSUE THREAD

**Issue by simPod** [camptocamp/grafana-prometheus-alertmanager-datasource#139]
Hi, this uses logo from https://github.com/simPod/GrafanaJsonDatasource

Should change.

**Comment by simPod** [comment]
https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/blob/62be0995951c71add6c031c113d342207e2a5bf8/src/img/json-logo.svg

**Comment by hbollon** [comment]
Hi @simPod and sorry for the late answer, I didn't have time to work on this since a while :grimacing: 
I wasn't here on project creation so I don't know why we have your plugin logo, I will change it asap.
