### ISSUE TITLE
Angular is deprecated - please migrate to React

### ISSUE THREAD

**Issue by tolzhabayev** [camptocamp/grafana-prometheus-alertmanager-datasource#144]
# Hello :wave: from Grafana Labs

We have detected that your plugin might still be using `AngularJS` and recommend migrating it to `React`, so that it may continue to operate successfully in future versions of Grafana.

You can read more on why and how by visiting our documentation: https://grafana.com/docs/grafana/latest/developers/angular_deprecation/

You can reach out to us with any questions via slack: [slack.grafana.com](https://slack.grafana.com) - channel `#plugins` or our [plugin development community forum](https://community.grafana.com/c/plugin-development/30)

**Comment by yarix** [comment]
we are on Grafana Cloud v10, this is how it looks like... are there any timelines to fix that? 🙏 
 
![image](https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/assets/6409857/a1fe8296-6698-4b6c-9088-2e3bde97ae9d)

**Comment by hbollon** [comment]
Hello, I didn't have time to work on this plugin since a while but I begin a migration to the new Grafana framework. It will be shipped ASAP, I'll keep you updated 👍

**Comment by hbollon** [comment]
Hi, I just released v2.0.0 of our plugin and published it on grafana.com. It's now built with React framework and compatible with latest versions of Grafana ! :partying_face: 
If you notice any issues with it or if you have enhancement suggestions, please open new issues.
