### ISSUE TITLE
Plugin doesn't work when Openalerts manager uses the alertmanager data source

### ISSUE THREAD

**Issue by dpachiappan** [camptocamp/grafana-prometheus-alertmanager-datasource#145]
Hi,

We have issues with Grafana open alerts manager dashboard import is failing with the error "Couldn't find a query runner that matches supplied arguments"

Upon debugging, it appears that the camp-to-camp datasource is not exporting the required variables expected by Grafana datasource causing the import to fail.

I have attached the screenshot here for reference. Could you let me know is this a known issue and how to fix it?

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/2790411/230533270-8d8ff8a6-218f-4e02-96c2-2a84bf025900.png">

**Comment by hbollon** [comment]
Hello, I guess you're talking about [this dashboard](https://grafana.com/grafana/dashboards/12947-open-alerts-of-alertmanager/) right?
If yes, it's not maintained by us so I invite you to check directly with the dashboard's author :wink:
