### ISSUE TITLE
Grafana11 Will not support Angular plugins

### ISSUE THREAD

**Issue by AyoubHabra** [camptocamp/grafana-prometheus-alertmanager-datasource#148]
Hello folks,
Grafana11 will not support Angular plugins, that says alert manager data source won't be supported by the coming releases of Grafana,  
Are you having any action plans for this ? Migration to React perhaps ? 
Please let us know if this will be fixed soon ? 
![image](https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/assets/73698006/c5b4fa1b-d5fb-4840-807d-0ecd63bb5844)

**Comment by csquire** [comment]
I would also like to know if there are plans to update this plugin. The sooner we know if the plugin will be deprecated, the sooner we can get users to move off of it.

**Comment by hbollon** [comment]
Hello, sorry for the delay.
I didn't have time to work on this plugin since a while but I begin a migration to the new Grafana framework. It will be shipped ASAP, I'll keep you updated :+1:

**Comment by hbollon** [comment]
I closed this issue in favor of #144, I will update the migration there :wink:
