### ISSUE TITLE
[release-0.0.4] plugin.json version=0.0.3 instead of 0.0.4

### ISSUE THREAD

**Issue by SPFZ** [camptocamp/grafana-prometheus-alertmanager-datasource#16]
Version number was not updated, therefore grafana says the version is 0.0.3.

**Comment by cryptobioz** [comment]
You're right, I forgot to update the plugin.json file. Now, it should be fixed.

**Comment by mjtrangoni** [comment]
@cryptobioz would you mind updating this [here](https://grafana.com/plugins/camptocamp-prometheus-alertmanager-datasource) too?

**Comment by cryptobioz** [comment]
A PR is open: https://github.com/grafana/grafana-plugin-repository/pull/253

**Comment by cryptobioz** [comment]
The PR has been merged. The version 0.0.4 is now available to download.
