### ISSUE TITLE
Graph history

### ISSUE THREAD

**Issue by Calange** [camptocamp/grafana-prometheus-alertmanager-datasource#19]
Hello,

Thank you for your great plugin, is there a way to have a graph history (like the number of alerts from the beginning) ?

Regards,

Calange

**Comment by cryptobioz** [comment]
It's not possible because the Alertmanager's API doesn't return timeseries.
In Prometheus, alerts are available as `ALERTS` metrics, maybe you can just use the Prometheus datasource to make your graphs?
