### ISSUE TITLE
TypeError in constructor

### ISSUE THREAD

**Issue by voronaam** [camptocamp/grafana-prometheus-alertmanager-datasource#24]
![screenshot](https://user-images.githubusercontent.com/2351069/39386105-d8b9ad3c-4a27-11e8-998f-58fa98bf72ca.png)

A dashboard we have that renders some data from Prometheus suddenly started to fail to work with the error seen on the above screenshot.

I tracked the error to https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/blob/master/dist/datasource.js#L45 file, the `instanceSettings.jsonData` is for some reason empty (`{}`).

**Comment by cryptobioz** [comment]
Did you define severity labels in the datasource configuration page? (cf. https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/pull/13#issue-166753373)

**Comment by voronaam** [comment]
We have not. Tried to define then now, it did not help. Still trying to understand why it is happening.

**Comment by cryptobioz** [comment]
Which version do you use?
