### ISSUE TITLE
Error 'e.text is undefined' on Grafana 5.1.0 and Firefox 59.0.2

### ISSUE THREAD

**Issue by njbartlett** [camptocamp/grafana-prometheus-alertmanager-datasource#25]
I am using plugin version 0.0.4 under Grafana 5.1.0 and using Firefox 59.0.2. The datasource installs and validates successfully, but when attempting to add a Table panel I get the error: `e.text is undefined` with the following stack trace:

```
[1623]/l</t.prototype.initColumns@http://localhost:3000/public/build/0.a84ed159b378acd7d9f2.js:7:302119
t@http://localhost:3000/public/build/0.a84ed159b378acd7d9f2.js:7:301793
[1620]/h</e.prototype.render@http://localhost:3000/public/build/0.a84ed159b378acd7d9f2.js:7:295060
[1620]/h</e.prototype.onDataReceived@http://localhost:3000/public/build/0.a84ed159b378acd7d9f2.js:7:294913
o.prototype.emit@http://localhost:3000/public/build/vendor.1f6280f6c83004ef1bab.js:44:25316
a</e.prototype.emit@http://localhost:3000/public/build/app.3095c117813e1134f897.js:1:13165
[1534]/f</e.prototype.handleQueryResult@http://localhost:3000/public/build/0.a84ed159b378acd7d9f2.js:7:18149
u@http://localhost:3000/public/build/vendor.1f6280f6c83004ef1bab.js:87:69119
l/<@http://localhost:3000/public/build/vendor.1f6280f6c83004ef1bab.js:87:69565
$digest@http://localhost:3000/public/build/vendor.1f6280f6c83004ef1bab.js:87:75262
$apply@http://localhost:3000/public/build/vendor.1f6280f6c83004ef1bab.js:87:77074
A/s<@http://localhost:3000/public/build/vendor.1f6280f6c83004ef1bab.js:87:73133
i@http://localhost:3000/public/build/vendor.1f6280f6c83004ef1bab.js:87:21976
me/l.defer/n<@http://localhost:3000/public/build/vendor.1f6280f6c83004ef1bab.js:87:23440
```

**Comment by njbartlett** [comment]
The same error also occurs under Grafana 5.0.3.

**Comment by njbartlett** [comment]
This error occurs when the user fails to select either `single` or `table` from the Format dropdown field, when creating a panel. So this isn't exactly a bug, but the error reporting could be better.

**Comment by cryptobioz** [comment]
I can't reproduce. Maybe a problem with your column names?

**Comment by njbartlett** [comment]
Steps to reproduce in my installation (Grafana 5.1.0, plugin 0.0.5):

1. Click "New dashboard"
2. Select "Table" from the New Panel type selector
3. Edit the panel, select a Prometheus Alertmanager datasource from the Data Source dropdown field.
4. Observe that a red corner appears at the top-left of the panel. Hovering over the corner shows the error message "Cannot read property 'match' of undefined".

**Comment by cryptobioz** [comment]
Thanks! You have to set the format "table".
