### ISSUE TITLE
[Question] Can this plugin show the history of alerts?

### ISSUE THREAD

**Issue by jinh-dk** [camptocamp/grafana-prometheus-alertmanager-datasource#29]
I would like to have a plugin not only show the current alerts, also can find the history of alerts.  Can I set the time range in this plugin to search the old alerts?

**Comment by njbartlett** [comment]
Probably not. In general Grafana does not store historical data -- we use Prometheus for that.

You can show a graph of historical alerts with a query such as `count(ALERTS{alertstate="firing"})`. To display this in Grafana, use the built-in Prometheus datasource.

**Comment by cryptobioz** [comment]
As @njbartlett said, Grafana doesn't store any data, you have to use Prometheus.
