### ISSUE TITLE
Add support for annotations

### ISSUE THREAD

**Issue by tlex** [camptocamp/grafana-prometheus-alertmanager-datasource#3]
Currently, only the labels are shown, but the annotations not. Typically, labels are used for the possibility to group items (in this case - alerts), not for displaying error messages, descriptions or URLs (for example: a link to a Wiki page).

Please add support for the alert annotations as well.

Thanks,
Alex

**Comment by madeinoz67** [comment]
would love to see this as well

**Comment by cryptobioz** [comment]
Great idea!
I added the support for alert annotations in the release 0.0.2.
By default, labels will be used but when adding a query, you can check the box "Use annotations" to switch to annotations.
