### ISSUE TITLE
Error displaying alerts in a table panel

### ISSUE THREAD

**Issue by sam-gaylert** [camptocamp/grafana-prometheus-alertmanager-datasource#33]
- Grafana 5.1.3

- Prometheus 2.2.1

- Alertmanager 0.15.0

- Alertmanager Plugin 0.0.5

When I try to display alerts in a table (the table transform is "time series to column") akin to the example in the documentation, I get the following error (shown in the top left corner): 

```Panel data error: TypeError: Cannot read property 'match' of undefined```

![screen shot 2018-06-04 at 1 26 35 pm](https://user-images.githubusercontent.com/17328188/40931999-01b246a4-67fb-11e8-940f-65edb639d282.png)

Has anyone else experienced this issue? I tried a few things such as editing the 'column styles' options to try and resolve the error but so far nothing has worked. There are currently no query expressions, and I a simply trying to display all alerts from prometheus in a table.

**Comment by cryptobioz** [comment]
Did you set the Format field to "table"?

**Comment by sam-gaylert** [comment]
Ah, this seems to have done the trick, thank you. I missed this in the example, my apologies.
