### ISSUE TITLE
Silenced Alerts

### ISSUE THREAD

**Issue by pete-leese** [camptocamp/grafana-prometheus-alertmanager-datasource#35]
I've tried a few different things but don't appear to be able to return the value for number of silenced alerts in a stat panel. 

Can you advise how I would achieve this? 

Cheers.

Pete

**Comment by sznmaran** [comment]
+1 

Nice to have!

It seems it's not possible in current version..
Url used to get data: "url: this.url + '/api/v1/alerts?silenced=false&inhibited=false&filter='+filter,"

**Comment by cryptobioz** [comment]
This feature has been implemented and will be available in the next release of this plugin.
