### ISSUE TITLE
Single Stat Panel - Sparklines not displaying

### ISSUE THREAD

**Issue by VR6Pete** [camptocamp/grafana-prometheus-alertmanager-datasource#36]
Hi There,

Using Prometheus Alert Manager as a datasource and configuring a single stat panel doesn't display the "Spark lines" when the option is checked.

When I revert back to the Prometheus data source then spark lines display as expected. 

Can you please advise?

**Comment by cryptobioz** [comment]
We can't do that because the Prometheus Alertmanager doesn't keep record of previous alerts. The datasource retrieve a list of alerts at one moment without history.
