### ISSUE TITLE
Unable to get alert rate from datasource

### ISSUE THREAD

**Issue by VR6Pete** [camptocamp/grafana-prometheus-alertmanager-datasource#37]
Hi,

As I switch over grafana to use this datasource for a more accurate alert figures I am trying to re-create the following graph that shows the rate of alerts over a period of time so i can look back historically, however struggling to re-create this with grafana-prometheus-alertmanager-datasource

_**count (irate(ALERTS{instance=~"$server"}[2m]))**_

**Comment by njbartlett** [comment]
That looks like a Prometheus query. Alertmanager itself doesn't support queries, it only supports basic filters on the labels attached to an alert. Those filters support simple equality such as `severity=3` and regexes such as `instance=~".*\.mydomain\.com"`. You cannot use functions or time ranges.

**Comment by VR6Pete** [comment]
Ok - Thanks for the clarification. 

I wonder if I can create a grafana query that subtracts the inhibited rules from my alert counts to calculate the alert rate using the Prometheus data source?

**Comment by njbartlett** [comment]
That sounds tricky as you would have to span two datasources -- Prometheus and Alertmanager. Probably not possible in Grafana.
