### ISSUE TITLE
Ordering of table data

### ISSUE THREAD

**Issue by VR6Pete** [camptocamp/grafana-prometheus-alertmanager-datasource#38]
Hi, 

I don't appear to be able to use sort_desc or the likes in the query to sort the data in the table.

I would like to order severity to display critical alerts at the top. 

cheers.

Pete

**Comment by njbartlett** [comment]
You don't need to sort the data in the query. The table control in Grafana will do sorting, just click the column header for the column you want to sort on.

**Comment by VR6Pete** [comment]
But that doesn’t
