### ISSUE TITLE
Add Support for Templating

### ISSUE THREAD

**Issue by jon-rei** [camptocamp/grafana-prometheus-alertmanager-datasource#4]
Currently you are not able to query with variable from templates.

It would be nice to add variables to your queries. For example like that:
- alertname="env_$env_number"
- alertname="env_[[env_number]]"

Please add support for using template variables in queries with the alertmanager datasource.

Regards,
Jonas

**Comment by cryptobioz** [comment]
I added the templating support in the [release 0.0.3](https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/releases/tag/0.0.3).

You can now write queries with variables.
