### ISSUE TITLE
useless config when first config

### ISSUE THREAD

**Issue by daixiang0** [camptocamp/grafana-prometheus-alertmanager-datasource#42]
At the first time to config:
```
Severity levels
Critical 4
High 3
Warning 2
Info 1
```
In readme, it seems `severity` desribe severity levels.

Then i set `severity` in first_rule.yaml and it can show in grafana, but those level can not convert to text as above config.

Is it a misunderstanding or a feature does not achieve?

**Comment by nicolasStevenin** [comment]
Hi !
It seems fine for me

![value to text](https://user-images.githubusercontent.com/17617687/45951678-be4e3a00-c004-11e8-88d8-f0fe5f23c8ec.PNG)

**Comment by daixiang0** [comment]
I can covert value to text by hand, but when i create a new dashboard using this datasource, it can not covert auotmaticlly.
