### ISSUE TITLE
Remove severity management from the datasource

### ISSUE THREAD

**Issue by cryptobioz** [camptocamp/grafana-prometheus-alertmanager-datasource#49]
Is it relevant to keep severity management in the datasource or would it be better to let the user manage this by itself?

**Comment by michael-doubez** [comment]
Being able to sort the alerts based on the severity tag is a nice feature. IMHO. I don't know if the datasource is the right place for that but it doesn't strike me as unreasonable.

**Comment by yarix** [comment]
i think its better to treat is as a simple label. 
it gets confusing when you define the mappings in the datasource and then again in the ui mapping

**Comment by cmunger** [comment]
+1 for yarix, I used your plugin and this severity add more confusion than anything else, and user can to its own sorting if needed

**Comment by steffersaurus** [comment]
Another +1. Our severity labels are based on values we're using in OpsGenie (P1-P5), and trying to map this correctly in the data source is still an issue.

**Comment by HaveFun83** [comment]
+1
