### ISSUE TITLE
Severity field is blank

### ISSUE THREAD

**Issue by gleb93** [camptocamp/grafana-prometheus-alertmanager-datasource#51]
Hello!
I've installed the latest version of your plugin (0.0.7) but `severity` field is still blank. 
Here is my config:
```
Critical 4
High 3
Warning 2
Info 1
``` 
![screen_alert_list](https://user-images.githubusercontent.com/10443450/52129648-b6507780-2640-11e9-8a10-bc9c0e99739b.png)

Both in Alertmanager and Prometheus alert marked as "severity=critical"
Any insights on how to fix this?

Thanks in advance!

**Comment by cryptobioz** [comment]
I think your severity labels configuration is wrong. In the plugin configuration, you should change the severity level for "Critical" from "4" to "critical".

**Comment by mvizcay** [comment]
Hi gleb93, did you solve it with value mappings?

Thanks.

**Comment by gleb93** [comment]
Yes, just as shown above. It didn’t work right away for some reason but resolved when alertmanager has started to send multiple alerts.
