### ISSUE TITLE
nwmatcher should be upgraded to version 1.4.4 or higher

### ISSUE THREAD

**Issue by amnonh** [camptocamp/grafana-prometheus-alertmanager-datasource#58]
There is a known security risk with nwmatcher. The current version used is too old.
Please update.
More about the issue:
https://snyk.io/vuln/npm:nwmatcher:20180305

**Comment by cryptobioz** [comment]
Thanks for the report! I updated all the dependencies, the project is now using the version 1.4.4 of nwmatcher.
