### ISSUE TITLE
Filter alerts by alertmanager receiver doubt

### ISSUE THREAD

**Issue by mbarper** [camptocamp/grafana-prometheus-alertmanager-datasource#67]
Hi,

I'm trying to filter the alerts from an alertmanager, but only those whose receivers are important to me. I can't find the way to do this filter, can somebody let me know if it is possible and how?

Regards,

**Comment by cryptobioz** [comment]
This feature has been implemented (0567785b18fd5c2ff61c01b87e6ed33a9c770441) and will be available in the next release of the plugin.
