### ISSUE TITLE
Support grafana 6.7

### ISSUE THREAD

**Issue by tlex** [camptocamp/grafana-prometheus-alertmanager-datasource#72]
In [grafana 6.7.0-beta1](https://github.com/grafana/grafana/blob/master/CHANGELOG.md#670-beta1-2020-03-12)  a breaking change has been introduced, that affects this plugin. See [Notice about changes in backendSrv for plugin authors](https://github.com/grafana/grafana/blob/master/CHANGELOG.md#notice-about-changes-in-backendsrv-for-plugin-authors).

With this upgrade, I currently get the following error:
`Window.fetch: HEAD or GET Request cannot have a body.`

**Comment by andreineustroev** [comment]
+1

**Comment by gdequidt** [comment]
+1

**Comment by checho13cadc** [comment]
I have the same probleam, any idea for fix this problem ?

**Comment by fx35** [comment]
+1

**Comment by rosaLux161** [comment]
+1

**Comment by wutkemtt** [comment]
+ 1 We are facing the same problem ...

**Comment by dphilpot** [comment]
+1

**Comment by sbaygithub** [comment]
+1

**Comment by cordula-grau** [comment]
+1

**Comment by xuanyuanaosheng** [comment]
any update?

**Comment by amnonh** [comment]
Can you please push an official release?
It's a shame to be forced to branch and maintain  a git branch just for this fix

**Comment by mkl262** [comment]
+1

**Comment by tlex** [comment]
Thanks, I can confirm it works. Until the official release, I've started my (docker) Grafana with the environment variable:
```
GF_INSTALL_PLUGINS=https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/archive/master.zip;camptocamp-prometheus-alertmanager-datasource
```

**Comment by Nklya** [comment]
I am wondering why there is no new release yet?
It's already > 1 month since everything got broken.
I am thinking now about just stop using this plugin.

**Comment by yarix** [comment]
hi @Nklya have you found an alternative plugin?

**Comment by krakazyabra** [comment]
Any updates? Grafana ver. v7.2.0-beta1 already released.

**Comment by Nklya** [comment]
It's already released long time ago and working fine.
