### ISSUE TITLE
[Bug] Cannot use more than 4 severity levels

### ISSUE THREAD

**Issue by sakishrist** [camptocamp/grafana-prometheus-alertmanager-datasource#79]
I do not see a way to use a 5th (or more) severity level and have it display on a table along side other severity levels.

Best case scenario, the severity label should not be touched and if the mapping feature is a must, should be done in a separate field/label with variable amount of mappings.

The way it is currently done is very intrusive and hinders usability.

Version of the plugin: 0.0.8

**Comment by cryptobioz** [comment]
The severity levels management will be removed in the next release of this plugin.
