### ISSUE TITLE
yarn build fails on babel dep

### ISSUE THREAD

**Issue by korenlev** [camptocamp/grafana-prometheus-alertmanager-datasource#80]
yarn build fails:

Running "babel:dist" (babel) task
Warning: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "/tmp/go/src/github.com/grafana/grafana/node_modules/@babel/preset-env/lib/index.js") Use --force to continue.

Aborted due to warnings.
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

ALSO:

error camptocamp-prometheus-alertmanager-datasource@0.0.1: The engine "node" is incompatible with this module. Expected version "6.10.0". Got "12.16.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

SOLUTION: 
1. remove 'node' dep from package.json
2. yarn add --dev babel-jest 'babel-core@^7.0.0-0' @babel/core regenerator-runtime

**Comment by cryptobioz** [comment]
As the plugin has been entirely rewritten, I think this issue isn't relevant anymore.
Please, fill free to reopen this issue if needed :)
