### ISSUE TITLE
Template variable regex values are double escaped and break queries

### ISSUE THREAD

**Issue by seanhoughton** [camptocamp/grafana-prometheus-alertmanager-datasource#81]
Template values are always regex format so you have to use the `=~` equality expression. However, the values appear to have special characters double escaped.

Repro:

Create a "custom" template variable `instance` with values `foo.com,bar.com`
Create a panel with the query `instance=~"$instance"`

The query going to alertmanager will have the query `silenced=false&inhibited=false&filter=instance%3D~%22foo%5C%5C.com%22`

Which decoded looks like:
`silenced=false&inhibited=false&filter=instance=~"foo\\.com"`

Alertmanager expects only a single escape character to ignore regex special characters.

**Comment by wangyf123** [comment]
Why it doesn't work when query with template variable on grafana alertmanger?
![image](https://user-images.githubusercontent.com/6194754/89979586-b81de100-dca2-11ea-96ac-bac2fc8310f8.png)
![image](https://user-images.githubusercontent.com/6194754/89979622-cd930b00-dca2-11ea-94fb-e84e192b51b6.png)

**Comment by wangyf123** [comment]
OK, I see based on description of the issue.

**Comment by wangyf123** [comment]
Solution test on my environment:
1. download the code
2. Modify camptocamp-prometheus-alertmanager-datasource/src/datasource.js dsSpecialRegexEscape:
![image](https://user-images.githubusercontent.com/6194754/90017660-714ddc80-dcde-11ea-92f6-117ba9b67629.png)
Remove the dot in regex.
3. rebuild  with npm
4. copy the camptocamp-prometheus-alertmanager-datasource to the grafana's /var/lib/grafana/plugins

**Comment by mjtrangoni** [comment]
@cryptobioz any news on this?

**Comment by cryptobioz** [comment]
I just published a commit which should fix this issue (https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/commit/ad8ba678ef80cf6889ca916671cd1bc9acbf43aa), could any of you test it to make sure it works as expected?

And thanks @wangyf123, I used your solution ;)

**Comment by hbollon** [comment]
This issue should be solved with the new release [v1.1.0](https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/releases/tag/v1.1.0).
