### ISSUE TITLE
label_values is ignoring the query when the key is set

### ISSUE THREAD

**Issue by david-ducos-percona** [camptocamp/grafana-prometheus-alertmanager-datasource#84]
I uploaded 4 images where I'm presenting the issue: 
<img width="685" alt="Screen Shot 2020-08-20 at 3 09 07 PM" src="https://user-images.githubusercontent.com/9828722/90809064-56d7bc80-e2f7-11ea-9dcf-2b26b138094a.png">
<img width="697" alt="Screen Shot 2020-08-20 at 3 08 38 PM" src="https://user-images.githubusercontent.com/9828722/90809079-59d2ad00-e2f7-11ea-9ba5-1f3aa7bfcacc.png">
<img width="755" alt="Screen Shot 2020-08-20 at 3 08 24 PM" src="https://user-images.githubusercontent.com/9828722/90809084-5a6b4380-e2f7-11ea-814d-33d84079e09c.png">
<img width="633" alt="Screen Shot 2020-08-20 at 3 08 08 PM" src="https://user-images.githubusercontent.com/9828722/90809089-5b03da00-e2f7-11ea-8639-cd4e89eb962f.png">

The issue is when I tried to filter by a node_name and the key is set.  The documentation says that "will return all the label values of the alerts returned by the query" but in my case it is returning the value of all the alerts which means that it is ignoring the query result

**Comment by hbollon** [comment]
Seems to be an invalid issue since this plugin doesn't support queries for variables atm.
In order to do that you must define a variable with raw values or query directly a Prometheus datasource.
