### ISSUE TITLE
Support multiple queries

### ISSUE THREAD

**Issue by jirislav** [camptocamp/grafana-prometheus-alertmanager-datasource#85]
Hi,

we are currently limited by creating a panel from only single query. We would love to make multiple queries to AlertManager, while letting Grafana take care of merging the results into the table.

I think that this part of code should be extended to iterate over all queries, instead of taking only first one.
https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/blob/7a541804bd0eb9f57797cf6a5dd0b6aa5bdd8ed8/src/datasource.js#L95-L98

Or another (probably much easier) approach would be to put all the queries into the single AlertManager call, which should be like this ([according to the sources of AM Alerts API](https://github.com/prometheus/alertmanager/blob/470634d49fc629727d91cbb271d7c6e9bc282b06/api/v2/api.go#L214)):

```diff
-/api/v1/alerts?silenced=false&inhibited=false&filter='+filter
+/api/v1/alerts?silenced=false&inhibited=false&filter[]='+filter1+'&filter[]='+filter2
```

**Comment by cryptobioz** [comment]
I'm currently rewriting this plugin and I just added this feature. You should be able to do that with the next release :)
