### ISSUE TITLE
Column filter not working

### ISSUE THREAD

**Issue by mirkan** [camptocamp/grafana-prometheus-alertmanager-datasource#86]
Hey,

Grafana recently launched column filters for table panels, but this seems to be not working so well with this datasource plugin. When selecting an object to filter, it clears/resets within a few seconds. It's like it does a refresh for the table.

Could this be fixed?

Thank you.

**Comment by hbollon** [comment]
Hi @mirkan,
I don't achieve to reproduce your issue, are you still experiencing it with the last release of this plugin?
