### ISSUE TITLE
Support Grafana 7+

### ISSUE THREAD

**Issue by naphta** [camptocamp/grafana-prometheus-alertmanager-datasource#87]
Currently having various issues in trying to make alerts show in a table view of Grafana. It doesn't look like there's support in the project for this version. Not sure how much work it is to make the change, but also unsure if this project is dead or not with the last major activity being months ago.

**Comment by manzsolutions-lpreis** [comment]
The plugin actually  stopped working with 6.7.0 already, the last version I can run it with is 6.6.2. This may be due to a [breaking change to backendSrv](https://github.com/grafana/grafana/releases/tag/v6.7.0-beta1).

> To remedy this issue, as a plugin author you need to trigger the digest after a direct call to backendSrv.
> 
> Example:
> 
> ```
> backendSrv.get(‘http://your.url/api’).then(result => {
>     this.result = result;
>     this.$scope.$digest();
> });
> ```

There are four calls to `backendSrv.datasourceRequest()` in [datasource.js](src/datasource.js) so it may be easily fixable for anyone who has the development environment (Yarn, NPX, etc.) set up. But it’s just a guess.

**Comment by ykuksenko** [comment]
Seems to work for me with 7.1.5. The main thing I haven't figured out is how to make the time show up correctly yet. (It would be nice to have silenced and inhibited alerts but that seems to be a missing feature at this time.)
My setup (in case it helps):
1. Deployed via docker
2. Install plugin (may need to review [this](https://grafana.com/docs/grafana/latest/plugins/plugin-signature-verification/#allow-unsigned-plugins), but seems to work without it for me)
3. Setup new alertmanager data source
4. Create a new "table" panel with the newly created data source. no query needed
5. In the panel config select format as "table".
6. Ensure there is an active alert in alertmanager.

**Comment by naphta** [comment]
As soon as I do a query on the data from alertmanager it just goes blank, these queries worked absolutely fine before the upgrade to 7.

**Comment by amnonh** [comment]
I've just written a new implementation using the updated Grafana SDK:
https://github.com/lalaux-design/alertmanager-ds

The implementation support the new grafana table format, and as a bonus also support graphs

**Comment by cryptobioz** [comment]
I started to rewrite this plugin, the next release will be fully compatible with Grafana v7.x.

**Comment by amnonh** [comment]
@cryptobioz if you want to you can use my implementation as a base:
https://github.com/lalaux-design/alertmanager-ds

**Comment by cryptobioz** [comment]
@amnonh Thanks, I'll have a look at it. I already published somes changes on `master`. Please, do not hesitate to open a PR or an issue if you see things that could be improved :)
