### ISSUE TITLE
BUG !!! Multiple queries show only one

### ISSUE THREAD

**Issue by herozabbix** [camptocamp/grafana-prometheus-alertmanager-datasource#88]
## How do I combine multiple queries

![image](https://user-images.githubusercontent.com/56722758/96214992-5aae5500-0faf-11eb-8f20-3113e85592a2.png)
![image](https://user-images.githubusercontent.com/56722758/96215012-6568ea00-0faf-11eb-8539-312658b4fe13.png)

**Comment by cryptobioz** [comment]
This issue is linked to #85 and will be fixed in the next release of the plugin.
