### ISSUE TITLE
Getting Query error: 502

### ISSUE THREAD

**Issue by manzajohn** [camptocamp/grafana-prometheus-alertmanager-datasource#91]
I have added the "grafana-prometheus-alertmanager-datasource " and while loading the datasource getting  Query error: 502 What could be the reason? Below are the grafana and alertmanager version
grafana - 7.0.3
alertmanager - 0.21.0

**Comment by manzajohn** [comment]
Below are the grafana and alertmanager version
grafana - 7.0.3
 alertmanager - 0.21.0

**Comment by cryptobioz** [comment]
Hi @manzajohn, do you get this error after you configured the datasource? Then you might need to change the datasource settings or check the availability of your Alertmanager.

**Comment by ebuildy** [comment]
Same thing here, got error after have configured data-source.

Grafana 7.4
alertmanager 0.21.0
