### ISSUE TITLE
publish version 1.0.0 to grafana plugins site

### ISSUE THREAD

**Issue by mattops** [camptocamp/grafana-prometheus-alertmanager-datasource#93]
Hi. I see version 1.0.0 which is more compatible with grafana 7.x is now on master.  Do you have a timeframe or plan to publish it to grafana plugins site?

**Comment by cryptobioz** [comment]
I opened a PR to add the release 1.0.0 to the official plugin list: https://github.com/grafana/grafana-plugin-repository/pull/868

**Comment by mattops** [comment]
I think the PR has failed a CI test: ```Unsupported metadata location
We found a plugin.json file in a dist directory. Since Grafana 7.3, we require plugin archives to contain a single directory that holds the contents of dist. The name of the directory must be the plugin ID. For more information, refer to Package a plugin.```

**Comment by el-psycho** [comment]
@mattops Thanks for the heads up.
@cryptobioz I've created PR [#96](https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/pull/96) which fixes most issues with only one error left (signing the package is required now).

**Comment by pgassmann** [comment]
@cryptobioz What's the status of the release to grafana.com? Last update was that you are looking into signing the plugin. What's blocking? Could you get access to your grafana Organization?

**Comment by cryptobioz** [comment]
I'm sorry, we're still waiting for a review by Grafana: https://github.com/grafana/grafana-plugin-repository/projects/2#card-54796691
