### ISSUE TITLE
Version 1.0.0 on master shows duplicate rows for alerts

### ISSUE THREAD

**Issue by el-psycho** [camptocamp/grafana-prometheus-alertmanager-datasource#95]
Version 1.0.0 as it currently looks on the master branch is displaying duplicate alert rows on the table panel.
![duplicate_alerts_present](https://user-images.githubusercontent.com/2379732/107718031-d8e2e580-6c89-11eb-8220-a4c78c906441.png)

PR #94 Fixes this.

**Comment by cryptobioz** [comment]
Thanks @el-psycho, fixed by #94.
