### ISSUE TITLE
Severity is not a number anymore - wrong sorting, no coloring

### ISSUE THREAD

**Issue by BluetriX** [camptocamp/grafana-prometheus-alertmanager-datasource#97]
Hi!

I use Grafana 7.3.5 and alertmanager-datasource 1.0.0

The severity value ist now "critical", "warning", "info" and no number anymore. So it is not possible to add colors by threshold and table sorting is wrong (info, critical, warning).

Is there a way for me to fix this or is it a plugin problem?

Thanks for this plugin! It helps a lot!

**Comment by BluetriX** [comment]
I solved it by addind severityValue to the datasource - see [PullRequest 98](https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/pull/98)

**Comment by jjneely** [comment]
I, too, was using this feature in 0.0.8

**Comment by juanjoku** [comment]
For now, I am still using version v0.0.8 because of this issue.....

**Comment by hbollon** [comment]
Hey !
I update and merged the PR associated :+1:
